name: 'Upload to IPFS'
description: 'The GitHub Action allows uploading DApps or content to IPFS. It supports IPFS, Pinata, Infura pinning services.'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  path:
    description: 'Directory path to upload'
    required: true
  service:
    description: 'Type of target service to upload. Supported services [ipfs, pinata, infura]'
    required: false
    default: 'ipfs'
  timeout:
    description: 'Request timeout'
    required: false
    default: 60000
  verbose:
    description: 'Level of verbosity'
    required: false
    default: false
  host:
    description: '[ipfs] IPFS host'
    required: false
    default: 'ipfs.komputing.org'
  port:
    description: '[ipfs] IPFS port'
    required: false
    default: 443
  protocol:
    description: '[ipfs] IPFS protocol'
    required: false
    default: 'https'
  headers:
    description: '[ipfs] IPFS headers as json object'
    required: false
    default: "{}"
  key:
    description: "[ipfs] IPNS key name. IPNS key will be published when the key parameter is provided. The key will be created if it does not exist"
    required: false
  pinataKey:
    description: '[pinata] Api Key. Required for pinata service'
    required: false
  pinataSecret:
    description: '[pinata] Secret Api Key. Required for pinata service'
    required: false
  pinataPinName:
    description: '[pinata] Human name for pin'
    required: false
  pinName:
    description: '[psa] Human name for pin'
    required: false
  filebaseBucket:
    description: '[filebase] Bucket Name. Required for Filebase service'
    required: false
  filebaseKey:
    description: '[filebase] Api Key. Required for Filebase service'
    required: false
  filebaseSecret:
    description: '[filebase] Secret Api Key. Required for Filebase service'
    required: false
outputs:
  hash:
    description: 'IPFS CID'
  cid:
    description: 'IPFS CID'
  ipfs:
    description: 'IPFS CID'
  ipns:
    description: 'IPNS CID if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
